spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    data: classpath:sql-scripts/h2/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect